declare const styles: {
  readonly "activityDate": string;
  readonly "activityDuration": string;
  readonly "activityItem": string;
  readonly "activityList": string;
  readonly "activityStatus": string;
  readonly "activityType": string;
  readonly "contentSection": string;
  readonly "departmentDashboard": string;
  readonly "departmentTable": string;
  readonly "header": string;
  readonly "headerActions": string;
  readonly "headerCell": string;
  readonly "kpiCard": string;
  readonly "kpiContent": string;
  readonly "kpiLabel": string;
  readonly "kpiSection": string;
  readonly "kpiSubtext": string;
  readonly "kpiValue": string;
  readonly "kpiVariance": string;
  readonly "sectionCard": string;
  readonly "sectionTitle": string;
  readonly "statusComplete": string;
  readonly "tableCell": string;
  readonly "tableHeader": string;
  readonly "tableRow": string;
  readonly "title": string;
  readonly "utilizationBar": string;
  readonly "utilizationFill": string;
  readonly "utilizationText": string;
  readonly "varianceHigh": string;
  readonly "varianceLow": string;
  readonly "varianceMedium": string;
};
export = styles;

