declare const styles: {
  readonly portalContainer: string;
  readonly header: string;
  readonly managerInfo: string;
  readonly viewSelector: string;
  readonly overviewCards: string;
  readonly costOverview: string;
  readonly variance: string;
  readonly budgetUtilization: string;
  readonly budgetDetails: string;
  readonly budgetItem: string;
  readonly spaceMetrics: string;
  readonly metricItem: string;
  readonly cardHeaderWithTooltip: string;
  readonly tooltipIcon: string;
  readonly locationsSection: string;
  readonly eventsSection: string;
  readonly eventsHeader: string;
  readonly actionButtons: string;
  readonly trendsSection: string;
  readonly trendPlaceholder: string;
  readonly success: string;
  readonly warning: string;
  readonly error: string;
  readonly renewal: string;
  readonly expiration: string;
  readonly change: string;
};

export default styles;