declare const styles: {
  readonly reportSystem: string;
  readonly tabsSection: string;
  readonly templateLibrary: string;
  readonly templateName: string;
  readonly templateDescription: string;
  readonly executive: string;
  readonly operational: string;
  readonly analytical: string;
  readonly scheduledSection: string;
  readonly sectionHeader: string;
  readonly distributionGroups: string;
  readonly distributionGroup: string;
  readonly groupInfo: string;
  readonly historySection: string;
  readonly active: string;
  readonly paused: string;
  readonly success: string;
  readonly failed: string;
  readonly completed: string;
  readonly processing: string;
  readonly actionButtons: string;
  readonly reportBuilder: string;
  readonly schedulingDialog: string;
  readonly builderSection: string;
  readonly configGrid: string;
  readonly configItem: string;
  readonly customDateRange: string;
  readonly filterSection: string;
  readonly checkboxGroup: string;
  readonly dialogActions: string;
  readonly generating: string;
};

export default styles;